version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=709170120355.dkr.ecr.eu-central-1.amazonaws.com/openquiz/main
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - dotnet tool restore
      - dotnet fake build -t docker
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag usix/openquiz:latest $REPOSITORY_URI:latest
      - docker tag usix/openquiz:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      #- echo Publishing static content...
      #- aws s3 sync deploy/public/ s3://open-quiz
      #- aws cloudfront create-invalidation --distribution-id E256EZ7OJAT9HC --paths '/*'